### ISSUE TITLE
Imagem no repo e dúvida

### ISSUE THREAD

**Issue by adhamlucas** [EnriqueIzel2/financas-app#1]
Projetinho pra uso pessoal mesmo ou se inspirou no Lucas Montano? hahah

Coloca imagem do app no Readme também ;)))

**Comment by EnriqueIzel2** [comment]
Não, é projeto de um curso que eu tô fazendo, mas quando finalizado vai ser pra uso pessoal

**Comment by adhamlucas** [comment]
Primeira vez usando uma issue kkkk

Tenho que entender melhor essas coisas do github
